"""Write src/Scenario/Curriculum/Character/SpecBuilds.cpp from builds.py (validate it first with validate.py).

    python3 tools/spec_builds/generate.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from builds import BUILDS, GLYPHS  # noqa: E402

CLASS_CONSTANTS = {"warrior": "CLASS_WARRIOR", "paladin": "CLASS_PALADIN", "hunter": "CLASS_HUNTER",
                   "rogue": "CLASS_ROGUE", "priest": "CLASS_PRIEST", "deathknight": "CLASS_DEATH_KNIGHT",
                   "shaman": "CLASS_SHAMAN", "mage": "CLASS_MAGE", "warlock": "CLASS_WARLOCK", "druid": "CLASS_DRUID"}

SOURCE_DIR = Path(__file__).resolve().parents[2] / "src" / "Scenario" / "Curriculum" / "Character"
LICENSE = (SOURCE_DIR / "TalentBuilder.cpp").read_text().split("*/", 1)[0] + "*/\n"


def quote(s):
    return '"' + s.replace('"', '\\"') + '"'


def wrap(items, indent, width=120):
    lines, cur = [], indent
    for item in items:
        piece = item + ","
        if len(cur) + len(piece) + 1 > width and cur.strip():
            lines.append(cur.rstrip())
            cur = indent
        cur += piece + " "
    if cur.strip():
        lines.append(cur.rstrip())
    return lines


out = [LICENSE, '#include "SpecBuilds.h"', '#include "SharedDefines.h"', "",
       "// Generated by tools/spec_builds/generate.py from builds.py, checked by validate.py (every build spends 71 points",
       "// and reaches every talent it names): standard 3.3.5 builds and glyphs. Talents are taken in list order, each point",
       "// going to the first talent that still wants ranks and may take one.", "",
       "std::vector<Animus::Curriculum::SpecBuild> const& Animus::Curriculum::SpecBuilds()", "{",
       "    static std::vector<SpecBuild> const builds =", "    {"]
for (cls, spec, page), build in BUILDS.items():
    majors, minors = GLYPHS[(cls, spec)]
    out.append(f"        {{ {CLASS_CONSTANTS[cls]}, {quote(spec)},")
    out.append("            {")
    out += wrap([f"{{ {tab}, {quote(name)}, {ranks} }}" for tab, name, ranks in build if ranks], "                ")
    out.append("            },")
    out.append("            { " + ", ".join(quote(g) for g in majors) + " },")
    out.append("            { " + ", ".join(quote(g) for g in minors) + " } },")
out += ["    };", "", "    return builds;", "}", "",
        "Animus::Curriculum::SpecBuild const* Animus::Curriculum::FindSpecBuild(uint8 playerClass,",
        "    std::string_view spec)",
        "{",
        "    for (SpecBuild const& build : SpecBuilds())",
        "        if (build.Class == playerClass && build.Spec == spec)",
        "            return &build;", "", "    return nullptr;", "}", ""]
path = SOURCE_DIR / "SpecBuilds.cpp"
open(path, "w").write("\n".join(out))
print("written", sum(1 for _ in BUILDS))
